# Generated by Django 3.1.1 on 2020-09-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=8)),
                ('tipo', models.CharField(choices=[('f5', 'Futbol 5'), ('f7', 'Futbol 7'), ('f11', 'Futbol 11')], max_length=3)),
                ('iluminacion', models.BooleanField(default=False)),
                ('vestuario', models.BooleanField(default=False)),
                ('cesped_sintetico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('empleado', models.CharField(max_length=50)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.cancha')),
            ],
        ),
    ]
